Add React 19 to peer peerDependencies
xiaolin/react-image-gallery pull request #807
Opened 2024-11-03 00:20 UTC by Yohannfra

2024-11-27 22:57 UTC, xiaolin commented on package.json
> +    "react": "^16.0.0 || ^17.0.0 || ^18.0.0 || ^19.0"
can we add the patch versioning in too `^19.0.0`

2024-11-27 22:58 UTC, xiaolin requested changes
left comment about patch versioning

2024-12-22 17:40 UTC, janie314 commented
See #809 . Will this branch add React 19 support? If not, I may be interested in implementing that over the holidays.

2024-12-22 19:21 UTC, xiaolin commented
> See #809 . Will this branch add React 19 support? If not, I may be interested in implementing that over the holidays.

This branch looks to be only a peer dependency update, feel free to open pr if react 19 does not work.

2025-02-11 02:48 UTC, xiaolin commented
fixed in #813

2025-02-11 02:48 UTC, closed without merging